site_name: Lark
theme: readthedocs
pages:
    - Main Page: index.md
    - Philosophy: philosophy.md
    - Features: features.md
    - Parsers: parsers.md
    - How To Use (Guide): how_to_use.md
    - How To Develop (Guide): how_to_develop.md
    - Grammar Reference: grammar.md
    - Tree Construction Reference: tree_construction.md
    - Visitors and Transformers: visitors.md
    - Classes Reference: classes.md
    - Recipes: recipes.md
